config/routes.rb
Bloog::Application.routes.draw do

  get "comments/new"

  get "comments/index"

resources :articles

=begin
  get "articles/index"

  get "articles/new"

  get "articles/show"

  get "articles/edit"

=end
  
root :to => "articles#index"
match "index" => "articles#index"

end

app/models/article.rb
class Article < ActiveRecord::Base
  attr_accessible :body, :title

  has_many :comments
  
  has_many :relationships
  has_many :categories, :through => :relationships



end

app/models/category.rb
class Category < ActiveRecord::Base
  attr_accessible :name
  
  has_many :relationships
  has_many :articles, :through => :relationships
  


end

app/models/comment.rb
class Comment < ActiveRecord::Base
  attr_accessible :article_id, :content

  belongs_to :article
end

app/models/relationship.rb
class Relationship < ActiveRecord::Base
  attr_accessible :article_id, :category_id
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  def index

  	@articles = Article.all

  end

  def new

    @article = Article.new
  	
  end

  def edit
  end

  def show

  @article = Article.find(params[:id])
  @comments = @article.comments
  session[:article_id] = @article.id

  end

def create

  @article = Article.create(params[:article])

  if @article.save
   
  redirect_to root_path

  else
 
  render 'new'

  end

end

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def new

 @comment = Comment.new 
  end

  def index
  end

  def create

    @comment = Comment.new(params[:comment])
    @article = @comment.article_id
   

    if @comment.save

    redirect_to article_path(@article)
   
    else
  
    render new


  end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/articles/edit.html.erb
<h1>Articles#edit</h1>
<p>Find me in app/views/articles/edit.html.erb</p>

app/views/articles/index.html.erb
<h1>Articles#index</h1>
<% @articles.each do |a| %>
<%= a.title %>
<%= a.body %> <br/>
<% end %>


<%= link_to "Create new article", new_article_path %>

app/views/articles/new.html.erb
<h1>Articles#new</h1>

<%= form_for (@article) do |f| %>
<p>
Title <br />
<%= f.text_field :title %>
</p> 

<p>Body <br />

<%= f.text_area :body %>


</p>

<%= f.submit "Send the Article!" %>

<% end %>


<p>Find me in app/views/articles/new.html.erb</p>

app/views/articles/show.html.erb
<h1>Articles#show</h1>
<p>Find me in app/views/articles/show.html.erb</p>

app/views/comments/index.html.erb
<h1>Comments#index</h1>
<p>Find me in app/views/comments/index.html.erb</p>

app/views/comments/new.html.erb
<h1>Comments#new</h1>

 
<% form_for(@comment) do |comment| %>
<%= comment.text_field :content %>

<% comment.hidden_field :article_id, :value => session[:article_id] %>

<% comment.submit "Send the comment!" %><



<% end %>
<p>Find me in app/views/comments/new.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Bloog</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>